### ISSUE TITLE
在安装完成之后 npm run dev   app.js 文件过大

### ISSUE THREAD

**Issue by lxyzxm** [pleaseyang/ItyWeb#1]
每次刷新网站时app.js文件都要44秒左右加载

**Comment by pleaseyang** [comment]
开发中 并没有遇到此问题 [（加载app.js需要68ms) ](http://47.95.37.116/storage/app.png)

可以参考[VUE-ELEMENT-ADMIN文档](https://panjiachen.github.io/vue-element-admin-site/zh/guide/#%E5%8A%9F%E8%83%BD)
