### ISSUE TITLE
关于 e-icon-picker 报错 复制 lib/e-icon-picker 到 node_modules

### ISSUE THREAD

**Issue by suyin12** [pleaseyang/ItyWeb#2]
为啥我还是有这个问题，反复执行
npm install
npm cache clean --force
npm run dev 
还是一样的问题，请问与 nodejs 版本有关？

![微信截图_20210809153706](https://user-images.githubusercontent.com/29671339/128674439-e78db442-6d60-4a57-b24e-e124b9a912b3.png)

**Comment by pleaseyang** [comment]
dist 没有推送上。 现在可以了
